version: "3.8"

services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: database-mongo
    ports:
      - "27017:27017"
    networks:
      - app-node-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-node-net
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - app-node-net
    depends_on:
      - backend

networks:
  app-node-net:
    driver: bridge