services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: database-mongo
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend